<?php
class MonriConstants
{
    const KEY_MODE = 'MONRI_MODE';
    const KEY_MERCHANT_KEY_PROD = 'MONRI_MERCHANT_KEY_PROD';
    const KEY_MERCHANT_KEY_TEST = 'MONRI_MERCHANT_KEY_TEST';
    const KEY_MERCHANT_AUTHENTICITY_TOKEN_PROD = 'MONRI_AUTHENTICITY_TOKEN_PROD';
    const KEY_MERCHANT_AUTHENTICITY_TOKEN_TEST = 'MONRI_AUTHENTICITY_TOKEN_TEST';
    const KEY_INTEGRATION_MODE = 'KEY_INTEGRATION_MODE';
    const KEY_KEEP_CONFIG_ON_RESET = 'KEY_KEEP_CONFIG_ON_RESET';
    const KEY_WEB_SERVICE_KEY = 'KEY_WEB_SERVICE_KEY';

    const MODE_PROD = 'prod';
    const MODE_TEST = 'test';
    const INTEGRATION_MODE_REDIRECT = 'INTEGRATION_MODE_REDIRECT';
    const INTEGRATION_MODE_EMBEDDED = 'INTEGRATION_MODE_EMBEDDED';
    const YES = 'YES';
    const NO = 'NO';
    const KEY_MIN_INSTALLMENTS = 'KEY_MIN_INSTALLMENTS';
    const KEY_MAX_INSTALLMENTS = 'KEY_MAX_INSTALLMENTS';
}