<?php
class MonriConstants
{
    const MODE_PROD = 'prod';
    const MODE_TEST = 'test';
    const KEY_MODE = 'MONRI_MODE';
    const KEY_MERCHANT_KEY_PROD = 'MONRI_MERCHANT_KEY_PROD';
    const KEY_MERCHANT_KEY_TEST = 'MONRI_MERCHANT_KEY_TEST';
    const KEY_MERCHANT_AUTHENTICITY_TOKEN_PROD = 'MONRI_AUTHENTICITY_TOKEN_PROD';
    const KEY_MERCHANT_AUTHENTICITY_TOKEN_TEST = 'MONRI_AUTHENTICITY_TOKEN_TEST';
    const KEY_MIN_INSTALLMENTS = 'KEY_MIN_INSTALLMENTS';
    const KEY_MAX_INSTALLMENTS = 'KEY_MAX_INSTALLMENTS';
}